add_definitions(-DX86_FEATURES)
list(APPEND ZLIB_ARCH_HDRS ${ARCHDIR}/x86_functions.h)
if(WITH_RUNTIME_CPU_DETECTION)
    list(APPEND ZLIB_ARCH_HDRS ${ARCHDIR}/x86_features.h)
    list(APPEND ZLIB_ARCH_SRCS ${ARCHDIR}/x86_features.c)
endif()

if(MSVC)
    list(APPEND ZLIB_ARCH_HDRS fallback_builtins.h)
endif()

check_xsave_intrinsics()
check_sse2_intrinsics()
check_ssse3_intrinsics()
check_sse41_intrinsics()
check_sse42_intrinsics()
check_avx2_intrinsics()
check_avx512_intrinsics()
check_avx512vnni_intrinsics()
check_pclmulqdq_intrinsics()
check_vpclmulqdq_intrinsics()

if(${ARCH} MATCHES "x86_64" AND ${WITH_X86_64_ARCHVER} GREATER_EQUAL "2" AND ${WITH_X86_64_ARCHVER} LESS_EQUAL "4")
    if(WITH_NATIVE_INSTRUCTIONS)
        MESSAGE(FATAL_ERROR "WITH_NATIVE_INSTRUCTIONS cannot be enabled together with WITH_X86_64_ARCHVER > 1")
    endif()
    add_definitions(-DZARCHVER=${WITH_X86_64_ARCHVER})
endif()

## Handle sets of instruction sets based on different x86-64 arch versions
# x86-64-v2 (up to SSE4.2)
if(${WITH_X86_64_ARCHVER} EQUAL "2")
    if(WITH_SSE2 AND HAVE_SSE2_INTRIN AND WITH_SSSE3 AND HAVE_SSSE3_INTRIN AND WITH_SSE41 AND HAVE_SSE41_INTRIN
        AND WITH_SSE42 AND HAVE_SSE42_INTRIN)

        add_definitions(-DX86_SSE2 -DX86_SSSE3 -DX86_SSE41 -DX86_SSE42)
        set(ARCHVER_SRCS ${ARCHDIR}/adler32_sse42.c ${ARCHDIR}/chunkset_ssse3.c ${ARCHDIR}/chorba_sse2.c ${ARCHDIR}/chorba_sse41.c ${ARCHDIR}/compare256_sse2.c ${ARCHDIR}/slide_hash_sse2.c)
        set_property(SOURCE ${ARCHVER_SRCS} PROPERTY COMPILE_FLAGS "${SSE42FLAG} ${NOLTOFLAG}")

        add_feature_info(SSE42_ADLER32 1 "Support SSE42-accelerated adler32, using \"${SSE42FLAG}\"")
        add_feature_info(SSSE3_CHUNKSET 1 "Support SSSE3-accelerated chunkset, using \"${SSE42FLAG}\"")
        add_feature_info(SSE41_CHORBA 1 "Support SSE41-accelerated chorba, using \"${SSE42FLAG}\"")
        add_feature_info(SSE2_COMPARE256 1 "Support SSE2-accelerated compare256, using \"${SSE42FLAG}\"")
        add_feature_info(SSE2_SLIDEHASH 1 "Support SSE2-accelerated slidehash, using \"${SSE42FLAG}\"")

    else()
        MESSAGE(FATAL_ERROR "WITH_X86_64_ARCHVER=2 Requires SSE2, SSSE3, SSE41 and SSE42, and their intrinsics to be supported and enabled.")
    endif()
endif()

# x86-64-v3 (up to AVX2)
if(${WITH_X86_64_ARCHVER} EQUAL "3")
    if(WITH_SSE2 AND HAVE_SSE2_INTRIN AND WITH_SSSE3 AND HAVE_SSSE3_INTRIN AND WITH_SSE41 AND HAVE_SSE41_INTRIN
        AND WITH_SSE42 AND HAVE_SSE42_INTRIN AND WITH_AVX2 AND HAVE_AVX2_INTRIN)

        add_definitions(-DX86_SSE2 -DX86_SSSE3 -DX86_SSE41 -DX86_SSE42 -DX86_AVX2)
        set(ARCHVER_SRCS ${ARCHDIR}/adler32_ssse3.c ${ARCHDIR}/adler32_sse42.c ${ARCHDIR}/adler32_avx2.c ${ARCHDIR}/chunkset_avx2.c ${ARCHDIR}/chorba_sse2.c ${ARCHDIR}/chorba_sse41.c ${ARCHDIR}/compare256_avx2.c ${ARCHDIR}/slide_hash_avx2.c)
        set_property(SOURCE ${ARCHVER_SRCS} PROPERTY COMPILE_FLAGS "${AVX2FLAG} ${NOLTOFLAG}")

        add_feature_info(AVX2_ADLER32 1 "Support AVX2-accelerated adler32, using \"${AVX2FLAG}\"")
        add_feature_info(AVX2_CHUNKSET 1 "Support AVX2-accelerated chunkset, using \"${AVX2FLAG}\"")
        add_feature_info(SSE41_CHORBA 1 "Support SSE41-accelerated chorba, using \"${AVX2FLAG}\"")
        add_feature_info(AVX2_COMPARE256 1 "Support AVX2-accelerated compare256, using \"${AVX2FLAG}\"")
        add_feature_info(AVX2_SLIDEHASH 1 "Support AVX2-accelerated slidehash, using \"${AVX2FLAG}\"")

    else()
        MESSAGE(FATAL_ERROR "WITH_X86_64_ARCHVER=2 Requires SSE2, SSSE3, SSE41, SSE42 and AVX2, and their intrinsics to be supported and enabled.")
    endif()
endif()

# x86-64-v4 (up to AVX512)
if(${WITH_X86_64_ARCHVER} EQUAL "4")
    if(WITH_SSE2 AND HAVE_SSE2_INTRIN AND WITH_SSSE3 AND HAVE_SSSE3_INTRIN AND WITH_SSE41 AND HAVE_SSE41_INTRIN
        AND WITH_SSE42 AND HAVE_SSE42_INTRIN AND WITH_AVX2 AND HAVE_AVX2_INTRIN AND WITH_AVX512 AND HAVE_AVX512_INTRIN)

        add_definitions(-DX86_SSE2 -DX86_SSSE3 -DX86_SSE41 -DX86_SSE42 -DX86_AVX2 -DX86_AVX512)
        set(ARCHVER_SRCS ${ARCHDIR}/adler32_ssse3.c ${ARCHDIR}/adler32_sse42.c ${ARCHDIR}/adler32_avx2.c ${ARCHDIR}/adler32_avx512.c ${ARCHDIR}/chunkset_avx512.c ${ARCHDIR}/chorba_sse2.c ${ARCHDIR}/chorba_sse41.c ${ARCHDIR}/compare256_avx512.c ${ARCHDIR}/slide_hash_avx2.c)
        list(APPEND ARCHVER_HDRS ${ARCHDIR}/adler32_avx512_p.h)
        set_property(SOURCE ${ARCHVER_SRCS} PROPERTY COMPILE_FLAGS "${AVX512FLAG} ${NOLTOFLAG}")

        add_feature_info(AVX512_ADLER32 1 "Support AVX512-accelerated adler32, using \"${AVX512FLAG}\"")
        add_feature_info(AVX512_CHUNKSET 1 "Support AVX512-accelerated chunkset, using \"${AVX512FLAG}\"")
        add_feature_info(SSE41_CHORBA 1 "Support SSE41-accelerated chorba, using \"${AVX512FLAG}\"")
        add_feature_info(AVX512_COMPARE256 1 "Support AVX512-accelerated compare256, using \"${AVX512FLAG}\"")
        add_feature_info(AVX2_SLIDEHASH 1 "Support AVX2-accelerated slidehash, using \"${AVX512FLAG}\"")

    else()
        MESSAGE(FATAL_ERROR "WITH_X86_64_ARCHVER=2 Requires SSE2, SSSE3, SSE41, SSE42, AVX2 and AVX512, and their intrinsics to be supported and enabled.")
    endif()
endif()

list(APPEND ZLIB_ARCH_SRCS ${ARCHVER_SRCS})
list(APPEND ZLIB_ARCH_HDRS ${ARCHVER_HDRS})


# Handle Individual instruction sets from x86-64-v1
if(NOT ${ARCH} MATCHES "x86_64" OR ${WITH_X86_64_ARCHVER} EQUAL "1")
    if(WITH_SSE2)
        if("${ARCH}" MATCHES "i[3-6]86")
            cmake_dependent_option(FORCE_SSE2 "Always assume CPU is SSE2 capable" OFF "HAVE_SSE2_INTRIN" OFF)
        endif()
        if(HAVE_SSE2_INTRIN)
            add_definitions(-DX86_SSE2)
            set(SSE2_SRCS ${ARCHDIR}/chunkset_sse2.c ${ARCHDIR}/chorba_sse2.c ${ARCHDIR}/compare256_sse2.c ${ARCHDIR}/slide_hash_sse2.c)
            list(APPEND ZLIB_ARCH_SRCS ${SSE2_SRCS})
            if(NOT ${ARCH} MATCHES "x86_64")
                set_property(SOURCE ${SSE2_SRCS} PROPERTY COMPILE_FLAGS "${SSE2FLAG} ${NOLTOFLAG}")
            endif()
        else()
            set(WITH_SSE2 OFF)
        endif()
    endif()

    if(WITH_SSSE3)
        if(HAVE_SSSE3_INTRIN AND WITH_SSE2)
            add_definitions(-DX86_SSSE3)
            set(SSSE3_SRCS ${ARCHDIR}/adler32_ssse3.c ${ARCHDIR}/chunkset_ssse3.c)
            add_feature_info(SSSE3_ADLER32 1 "Support SSSE3-accelerated adler32, using \"${SSSE3FLAG}\"")
            list(APPEND ZLIB_ARCH_SRCS ${SSSE3_SRCS})
            set_property(SOURCE ${SSSE3_SRCS} PROPERTY COMPILE_FLAGS "${SSSE3FLAG} ${NOLTOFLAG}")
        else()
            set(WITH_SSSE3 OFF)
        endif()
    endif()

    if(WITH_SSE41)
        if(HAVE_SSE41_INTRIN AND WITH_SSSE3)
            add_definitions(-DX86_SSE41)
            set(SSE41_SRCS ${ARCHDIR}/chorba_sse41.c)
            list(APPEND ZLIB_ARCH_SRCS ${SSE41_SRCS})
            set_property(SOURCE ${SSE41_SRCS} PROPERTY COMPILE_FLAGS "${SSE41FLAG} ${NOLTOFLAG}")
        else()
            set(WITH_SSE41 OFF)
        endif()
    endif()

    if(WITH_SSE42)
        if(HAVE_SSE42_INTRIN AND WITH_SSE41)
            add_definitions(-DX86_SSE42)
            set(SSE42_SRCS ${ARCHDIR}/adler32_sse42.c)
            add_feature_info(SSE42_CRC 1 "Support SSE4.2 optimized adler32 hash generation, using \"${SSE42FLAG}\"")
            list(APPEND ZLIB_ARCH_SRCS ${SSE42_SRCS})
            set_property(SOURCE ${SSE42_SRCS} PROPERTY COMPILE_FLAGS "${SSE42FLAG} ${NOLTOFLAG}")
        else()
            set(WITH_SSE42 OFF)
        endif()
    endif()
endif()

# Handle Individual instruction sets from x86-64-v2
if(NOT ${ARCH} MATCHES "x86_64" OR ${WITH_X86_64_ARCHVER} LESS_EQUAL "2")
    if(WITH_AVX2)
        if(HAVE_AVX2_INTRIN AND WITH_SSE42)
            add_definitions(-DX86_AVX2)
            set(AVX2_SRCS ${ARCHDIR}/adler32_avx2.c)
            add_feature_info(AVX2_ADLER32 1 "Support AVX2-accelerated adler32, using \"${AVX2FLAG}\"")
            list(APPEND AVX2_SRCS ${ARCHDIR}/chunkset_avx2.c)
            add_feature_info(AVX2_CHUNKSET 1 "Support AVX2 optimized chunkset, using \"${AVX2FLAG}\"")
            list(APPEND AVX2_SRCS ${ARCHDIR}/compare256_avx2.c)
            add_feature_info(AVX2_COMPARE256 1 "Support AVX2 optimized compare256, using \"${AVX2FLAG}\"")
            list(APPEND AVX2_SRCS ${ARCHDIR}/slide_hash_avx2.c)
            add_feature_info(AVX2_SLIDEHASH 1 "Support AVX2 optimized slide_hash, using \"${AVX2FLAG}\"")
            list(APPEND ZLIB_ARCH_SRCS ${AVX2_SRCS})
            set_property(SOURCE ${AVX2_SRCS} PROPERTY COMPILE_FLAGS "${AVX2FLAG} ${NOLTOFLAG}")
        else()
            set(WITH_AVX2 OFF)
        endif()
    endif()
endif()

# Handle Individual instruction sets from x86-64-v3
if(NOT ${ARCH} MATCHES "x86_64" OR ${WITH_X86_64_ARCHVER} LESS_EQUAL "3")
    if(WITH_AVX512)
        if(HAVE_AVX512_INTRIN AND WITH_AVX2)
            add_definitions(-DX86_AVX512)
            list(APPEND AVX512_SRCS ${ARCHDIR}/adler32_avx512.c)
            add_feature_info(AVX512_ADLER32 1 "Support AVX512-accelerated adler32, using \"${AVX512FLAG}\"")
            list(APPEND AVX512_SRCS ${ARCHDIR}/chunkset_avx512.c)
            add_feature_info(AVX512_CHUNKSET 1 "Support AVX512 optimized chunkset, using \"${AVX512FLAG}\"")
            list(APPEND AVX512_SRCS ${ARCHDIR}/compare256_avx512.c)
            add_feature_info(AVX512_COMPARE256 1 "Support AVX512 optimized compare256, using \"${AVX512FLAG}\"")
            list(APPEND ZLIB_ARCH_HDRS ${ARCHDIR}/adler32_avx512_p.h)
            list(APPEND ZLIB_ARCH_SRCS ${AVX512_SRCS})
            set_property(SOURCE ${AVX512_SRCS} PROPERTY COMPILE_FLAGS "${AVX512FLAG} ${NOLTOFLAG}")
        else()
            set(WITH_AVX512 OFF)
        endif()
    endif()
endif()

# Handle Individual instruction sets not part of any arch-version
if(HAVE_XSAVE_INTRIN)
    add_feature_info(XSAVE 1 "Support XSAVE intrinsics using \"${XSAVEFLAG}\"")
    if(WITH_RUNTIME_CPU_DETECTION)
        set_property(SOURCE ${ARCHDIR}/x86_features.c PROPERTY COMPILE_FLAGS "${XSAVEFLAG}")
    endif()
    if(NOT (CMAKE_C_COMPILER_ID MATCHES "GNU" AND CMAKE_C_COMPILER_VERSION VERSION_LESS 8.2))
        add_definitions(-DX86_HAVE_XSAVE_INTRIN)
    endif()
endif()

if(WITH_PCLMULQDQ)
    if(HAVE_PCLMULQDQ_INTRIN AND WITH_SSE42)
        add_definitions(-DX86_PCLMULQDQ_CRC)
        set(PCLMULQDQ_SRCS ${ARCHDIR}/crc32_pclmulqdq.c)
        add_feature_info(PCLMUL_CRC 1 "Support CRC hash generation using PCLMULQDQ, using \"${SSE42FLAG} ${PCLMULFLAG}\"")
        list(APPEND ZLIB_ARCH_SRCS ${PCLMULQDQ_SRCS})
        set_property(SOURCE ${PCLMULQDQ_SRCS} PROPERTY COMPILE_FLAGS "${SSE42FLAG} ${PCLMULFLAG} ${NOLTOFLAG}")
    else()
        set(WITH_PCLMULQDQ OFF)
    endif()
endif()

if(WITH_VPCLMULQDQ)
    if(HAVE_VPCLMULQDQ_INTRIN AND WITH_PCLMULQDQ AND WITH_AVX512)
        add_definitions(-DX86_VPCLMULQDQ_CRC)
        set(VPCLMULQDQ_SRCS ${ARCHDIR}/crc32_vpclmulqdq.c)
        add_feature_info(VPCLMUL_CRC 1 "Support CRC hash generation using VPCLMULQDQ, using \"${PCLMULFLAG} ${VPCLMULFLAG} ${AVX512FLAG}\"")
        list(APPEND ZLIB_ARCH_SRCS ${VPCLMULQDQ_SRCS})
        set_property(SOURCE ${VPCLMULQDQ_SRCS} PROPERTY COMPILE_FLAGS "${PCLMULFLAG} ${VPCLMULFLAG} ${AVX512FLAG} ${NOLTOFLAG}")
    else()
        set(WITH_VPCLMULQDQ OFF)
    endif()
endif()

if(WITH_AVX512VNNI)
    if(HAVE_AVX512VNNI_INTRIN AND WITH_AVX2)
        add_definitions(-DX86_AVX512VNNI)
        add_feature_info(AVX512VNNI_ADLER32 1 "Support AVX512VNNI adler32, using \"${AVX512VNNIFLAG}\"")
        list(APPEND AVX512VNNI_SRCS ${ARCHDIR}/adler32_avx512_vnni.c)
        if(${WITH_X86_64_ARCHVER} EQUAL "2")
            add_definitions(-DX86_SSSE3)
            list(APPEND AVX512VNNI_SRCS ${ARCHDIR}/adler32_ssse3.c)
        endif()
        list(APPEND ZLIB_ARCH_SRCS ${AVX512VNNI_SRCS})
        set_property(SOURCE ${AVX512VNNI_SRCS} PROPERTY COMPILE_FLAGS "${AVX512VNNIFLAG} ${NOLTOFLAG}")
    else()
        set(WITH_AVX512VNNI OFF)
    endif()
endif()

