name: OSS-Fuzz
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - stable
      - develop
      - pre-release
      - '2.*'
    tags:
      - '*'
concurrency:
  # Group by workflow name and branch/PR to only cancel runs on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  # Only cancels in-progress runs if the branch is not 'stable' or 'develop'
  cancel-in-progress: ${{ !contains(fromJSON('["refs/heads/stable", "refs/heads/develop"]'), github.ref) }}

jobs:
  fuzzing:
    name: Fuzzing
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'zlib-ng'
        dry-run: false

    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'zlib-ng'
        fuzz-seconds: 600
        dry-run: false

    - name: Upload Crash
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts
