name: Link
on: [workflow_call, workflow_dispatch]
jobs:
  zlib:
    name: Link zlib
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        show-progress: 'false'

    - name: Checkout zlib repository
      uses: actions/checkout@v6
      with:
        show-progress: 'false'
        repository: madler/zlib
        path: zlib

    - name: Generate project files (zlib)
      run: cmake -S zlib -B zlib/build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF

    - name: Compile source code (zlib)
      run: cmake --build zlib/build -j5 --config Release

    - name: Generate project files (native)
      run: cmake -S . -B native -DZLIB_COMPAT=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DZLIB_LIBRARIES=../zlib/build/libz.a -DZLIB_INCLUDE_DIR="../zlib/build;../zlib"

    - name: Compile source code (native)
      run: cmake --build native -j5 --config Release

    - name: Upload build errors
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: Link zlib (CMake Logs)
        path: |
          **/CMakeFiles/CMakeOutput.log
          **/CMakeFiles/CMakeError.log
        retention-days: 30

  zlib-ng-compat:
    name: Link zlib-ng compat
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        show-progress: 'false'

    - name: Generate project files (compat)
      run: cmake -S . -B compat -DZLIB_COMPAT=ON -DZLIB_ENABLE_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DWITH_MAINTAINER_WARNINGS=ON

    - name: Compile source code (compat)
      run: cmake --build compat -j5 --config Release

    - name: Generate project files (native)
      run: cmake -S . -B native -DZLIB_COMPAT=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DZLIB_LIBRARIES=../compat/libz.a -DZLIB_INCLUDE_DIR=../compat

    - name: Compile source code (native)
      run: cmake --build native -j5 --config Release

    - name: Upload build errors
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: Link zlib-ng compat (CMake Logs)
        path: |
          **/CMakeFiles/CMakeOutput.log
          **/CMakeFiles/CMakeError.log
        retention-days: 30

  find-package:
    name: Find package (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: native
            cmake-args: -DZLIB_COMPAT=OFF

          - name: compat
            cmake-args: -DZLIB_COMPAT=ON
            consumer-args: -DCONSUMER_ZLIB_COMPAT=ON

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        show-progress: 'false'

    - name: Generate project files (zlib-ng)
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF ${{ matrix.cmake-args }}

    - name: Compile source code (zlib-ng)
      run: cmake --build build --config Release --target zlib-ng

    - name: Generate project files (consumer)
      run: cmake -S test/find-package-project -B consumer -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$PWD/build ${{ matrix.consumer-args }}

    - name: Compile source code (consumer)
      run: cmake --build consumer --config Release

    - name: Run consumer
      run: ./consumer/app

    - name: Upload build errors
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: Find package ${{ matrix.name }} (CMake Logs)
        path: |
          **/CMakeFiles/CMakeOutput.log
          **/CMakeFiles/CMakeError.log
        retention-days: 30
