name: Orchestrator
on: [push, pull_request, workflow_dispatch]
concurrency:
  # Group by workflow name and branch/PR to only cancel runs on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  # Only cancels in-progress runs if the branch is not 'stable' or 'develop'
  cancel-in-progress: ${{ !contains(fromJSON('["refs/heads/stable", "refs/heads/develop"]'), github.ref) }}

jobs:
  # Workflows not handled here: fuzz, lint, release

  # OSB runs first, the rest won't start unless it succeeds
  # This guards against spending a lot of time testing code that is unable to compile.
  osb:
    name: OSB
    uses: ./.github/workflows/osb.yml
    secrets: inherit

  analyze:
    name: Static Analysis
    needs: osb
    uses: ./.github/workflows/analyze.yml
    secrets: inherit

  cmake:
    name: CMake
    needs: osb
    uses: ./.github/workflows/cmake.yml
    secrets: inherit

  codeql:
    name: CodeQL
    needs: osb
    uses: ./.github/workflows/codeql.yml
    secrets: inherit

  configure:
    name: Configure
    needs: osb
    uses: ./.github/workflows/configure.yml
    secrets: inherit

  libpng:
    name: Libpng
    needs: osb
    uses: ./.github/workflows/libpng.yml
    secrets: inherit

  link:
    name: Link
    needs: osb
    uses: ./.github/workflows/link.yml
    secrets: inherit

  pigz:
    name: Pigz
    needs: osb
    uses: ./.github/workflows/pigz.yml
    secrets: inherit

  pkgcheck:
    name: Package Check
    needs: osb
    uses: ./.github/workflows/pkgcheck.yml
    secrets: inherit

  # This job only starts if both cmake and pigz workflows above succeed
  final-upload:
    needs: [cmake, pigz]
    runs-on: ubuntu-slim
    if: success()
    steps:
      - name: Coveralls - Finalize
        uses: coverallsapp/github-action@v2
        if: (env.COVERALLS_REPO_TOKEN != '' || github.repository == 'zlib-ng/zlib-ng')
        with:
          parallel-finished: true
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
